### ISSUE TITLE
branch 14 TX2NX ./setup.sh -c brings up wrong DT file

### ISSUE THREAD

**Issue by sb3d-tech-mteitel** [VC-MIPI-modules/vc_mipi_nvidia#45]
enter 8-1 in config script.
./setup.sh -camera brings up:
vc_mipi_nvidia/src/devicetree/Auvidea_J20_AGXXavier/tegra194-camera-vc-mipi-cam.dtsi

should bring up 
home/mat/sb3d/newtx2nx/vc_mipi_nvidia/src/devicetree/Auvidea_JNX30D_TX2NX/tegra186-camera-vc-mipi-cam.dtsi

**Comment by pmliquify** [comment]
This issue will be solved with #44

**Comment by pmliquify** [comment]
This issue is solved with Release 0.15.0
