### ISSUE TITLE
IMX568 image not ok on Jetson nano

### ISSUE THREAD

**Issue by VC-Support** [VC-MIPI-modules/vc_mipi_nvidia#55]
Test setup: JNX30 + Jetson nano with L4T 32.6.1 and driver 0.14.1.

When streaming (mode does not seem to matter, for example 2 lanes, 10-bit, streaming mode) with the standard resolution (2472 x 2048) the image is not ok. It looks like the image width is wrong. When the image width is changed to 2432, 2464 or 2496 for example, 1 image out of 3 image look good and 2 out of 3 images are black. Additionnally the kernel log output the error message "image height is too long" (or too short).

**Comment by bazo80** [comment]
Has been fixed with Release 0.16.0
https://github.com/VC-MIPI-modules/vc_mipi_nvidia/blob/v0.16.0/VERSION.md
